export default {
  '@context': '/api/contexts/Configuration',
  '@id': '/api/configurations',
  '@type': 'hydra:Collection',
  'hydra:member': [
    {
      '@id': '/api/configurations/1',
      '@type': 'Configuration',
      name: 'Ideal for storage',
      chassis: {
        '@id': '/api/chassis/1',
        '@type': 'Chassis',
        displayName: 'Fujitsu PRIMERGY RX1330 M3',
      },
      cpuOptions: ['/api/cpus/11'],
      cpu: '/api/cpus/11',
      gpu: null,
      locationOptions: ['/api/locations/1'],
      location: '/api/locations/1',
      trafficOptions: [],
      traffic: null,
      uplinkOptions: [
        '/api/uplinks/1',
        '/api/uplinks/2',
        '/api/uplinks/3',
        '/api/uplinks/4',
        '/api/uplinks/5',
        '/api/uplinks/6',
        '/api/uplinks/7',
        '/api/uplinks/8',
        '/api/uplinks/9',
        '/api/uplinks/10',
        '/api/uplinks/11',
        '/api/uplinks/12',
      ],
      uplink: '/api/uplinks/1',
      localUplinkOptions: ['/api/local_uplinks/1', '/api/local_uplinks/2'],
      localUplink: null,
      ddosShieldOptions: [
        '/api/ddos_shields/1',
        '/api/ddos_shields/2',
        '/api/ddos_shields/3',
        '/api/ddos_shields/4',
        '/api/ddos_shields/5',
        '/api/ddos_shields/6',
      ],
      ddosShield: '/api/ddos_shields/1',
      hardwareFirewallOptions: ['/api/hardware_firewalls/2'],
      hardwareFirewall: null,
      storageOptions: [
        '/api/storage_drives/1',
        '/api/storage_drives/2',
        '/api/storage_drives/3',
        '/api/storage_drives/4',
        '/api/storage_drives/5',
        '/api/storage_drives/6',
        '/api/storage_drives/7',
        '/api/storage_drives/8',
        '/api/storage_drives/9',
        '/api/storage_drives/10',
        '/api/storage_drives/11',
        '/api/storage_drives/12',
        '/api/storage_drives/13',
        '/api/storage_drives/14',
        '/api/storage_drives/15',
        '/api/storage_drives/16',
        '/api/storage_drives/17',
        '/api/storage_drives/18',
        '/api/storage_drives/19',
        '/api/storage_drives/20',
        '/api/storage_drives/21',
        '/api/storage_drives/22',
        '/api/storage_drives/23',
        '/api/storage_drives/24',
      ],
      storage: '/api/storage_drives/10',
      ipMaxAmount: 4,
      cPanel: true,
      directAdmin: true,
      backup: true,
      threadstone: true,
      tags: [],
    },
    {
      '@id': '/api/configurations/2',
      '@type': 'Configuration',
      name: 'Ideal for streaming',
      chassis: {
        '@id': '/api/chassis/2',
        '@type': 'Chassis',
        displayName: 'Fujitsu PRIMERGY RX2510 M2',
      },
      cpuOptions: ['/api/cpus/4', '/api/cpus/5'],
      cpu: '/api/cpus/4',
      gpu: null,
      locationOptions: ['/api/locations/1', '/api/locations/2'],
      location: '/api/locations/1',
      trafficOptions: [],
      traffic: null,
      uplinkOptions: [
        '/api/uplinks/1',
        '/api/uplinks/2',
        '/api/uplinks/3',
        '/api/uplinks/4',
        '/api/uplinks/5',
        '/api/uplinks/6',
        '/api/uplinks/7',
        '/api/uplinks/8',
        '/api/uplinks/9',
        '/api/uplinks/10',
        '/api/uplinks/11',
        '/api/uplinks/12',
      ],
      uplink: '/api/uplinks/10',
      localUplinkOptions: ['/api/local_uplinks/1', '/api/local_uplinks/2'],
      localUplink: '/api/local_uplinks/2',
      ddosShieldOptions: [
        '/api/ddos_shields/1',
        '/api/ddos_shields/2',
        '/api/ddos_shields/3',
        '/api/ddos_shields/4',
        '/api/ddos_shields/5',
        '/api/ddos_shields/6',
      ],
      ddosShield: '/api/ddos_shields/6',
      hardwareFirewallOptions: ['/api/hardware_firewalls/1', '/api/hardware_firewalls/2'],
      hardwareFirewall: '/api/hardware_firewalls/2',
      storageOptions: [
        '/api/storage_drives/1',
        '/api/storage_drives/2',
        '/api/storage_drives/3',
        '/api/storage_drives/4',
        '/api/storage_drives/5',
        '/api/storage_drives/6',
        '/api/storage_drives/7',
        '/api/storage_drives/8',
        '/api/storage_drives/9',
        '/api/storage_drives/10',
        '/api/storage_drives/11',
        '/api/storage_drives/12',
        '/api/storage_drives/13',
        '/api/storage_drives/14',
        '/api/storage_drives/15',
        '/api/storage_drives/16',
        '/api/storage_drives/17',
        '/api/storage_drives/18',
        '/api/storage_drives/19',
        '/api/storage_drives/20',
        '/api/storage_drives/21',
        '/api/storage_drives/22',
        '/api/storage_drives/23',
        '/api/storage_drives/24',
      ],
      storage: '/api/storage_drives/10',
      ipMaxAmount: 4,
      cPanel: false,
      directAdmin: false,
      backup: false,
      threadstone: false,
      tags: [],
    },
  ],
  'hydra:totalItems': 2,
}
