export default {
  '@context': '/api/contexts/Cpu',
  '@id': '/api/cpus',
  '@type': 'hydra:Collection',
  'hydra:member': [
    {
      '@id': '/api/cpus/1',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Core',
      model: 'i3-2100',
      speed: 310,
      cores: 2,
      smt: true,
      prices: [],
      displayName: 'Intel Core i3-2100',
    },
    {
      '@id': '/api/cpus/2',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Core',
      model: 'i5-2500K',
      speed: 330,
      cores: 4,
      smt: false,
      prices: [],
      displayName: 'Intel Core i5-2500K',
    },
    {
      '@id': '/api/cpus/3',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Core',
      model: 'i7-2600K',
      speed: 340,
      cores: 4,
      smt: true,
      prices: [],
      displayName: 'Intel Core i7-2600K',
    },
    {
      '@id': '/api/cpus/4',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E3-1230v2',
      speed: 330,
      cores: 4,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon E3-1230v2',
    },
    {
      '@id': '/api/cpus/5',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E3-1270v2',
      speed: 350,
      cores: 4,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon E3-1270v2',
    },
    {
      '@id': '/api/cpus/6',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E3-1246v3',
      speed: 350,
      cores: 4,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon E3-1246v3',
    },
    {
      '@id': '/api/cpus/7',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E3-1276v3',
      speed: 360,
      cores: 4,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon E3-1276v3',
    },
    {
      '@id': '/api/cpus/8',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E3-1240L v5',
      speed: 210,
      cores: 4,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon E3-1240L v5',
    },
    {
      '@id': '/api/cpus/9',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E3-1220v6',
      speed: 300,
      cores: 4,
      smt: false,
      prices: [],
      displayName: 'Intel Xeon E3-1220v6',
    },
    {
      '@id': '/api/cpus/10',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E3-1230v6',
      speed: 350,
      cores: 4,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon E3-1230v6',
    },
    {
      '@id': '/api/cpus/11',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E3-1270v6',
      speed: 380,
      cores: 4,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon E3-1270v6',
    },
    {
      '@id': '/api/cpus/12',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E5620',
      speed: 240,
      cores: 4,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon E5620',
    },
    {
      '@id': '/api/cpus/13',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E5-2420v2',
      speed: 220,
      cores: 6,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon E5-2420v2',
    },
    {
      '@id': '/api/cpus/14',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E5-2450L',
      speed: 180,
      cores: 8,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon E5-2450L',
    },
    {
      '@id': '/api/cpus/15',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E5-2620v0',
      speed: 200,
      cores: 6,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon E5-2620v0',
    },
    {
      '@id': '/api/cpus/16',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E5-2620v2',
      speed: 210,
      cores: 6,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon E5-2620v2',
    },
    {
      '@id': '/api/cpus/17',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E5-2620v3',
      speed: 240,
      cores: 6,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon E5-2620v3',
    },
    {
      '@id': '/api/cpus/18',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E5-2620v4',
      speed: 210,
      cores: 8,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon E5-2620v4',
    },
    {
      '@id': '/api/cpus/19',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E5-2640v4',
      speed: 240,
      cores: 10,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon E5-2640v4',
    },
    {
      '@id': '/api/cpus/20',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'Silver 4108',
      speed: 180,
      cores: 8,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon Silver 4108',
    },
    {
      '@id': '/api/cpus/21',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E5-2660v4',
      speed: 200,
      cores: 14,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon E5-2660v4',
    },
    {
      '@id': '/api/cpus/22',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'Gold 5120',
      speed: 220,
      cores: 14,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon Gold 5120',
    },
    {
      '@id': '/api/cpus/23',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'E5-2690v4',
      speed: 260,
      cores: 14,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon E5-2690v4',
    },
    {
      '@id': '/api/cpus/24',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Xeon',
      model: 'Gold 6130',
      speed: 210,
      cores: 16,
      smt: true,
      prices: [],
      displayName: 'Intel Xeon Gold 6130',
    },
    {
      '@id': '/api/cpus/25',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'C2Q',
      model: 'Q8400',
      speed: 266,
      cores: 4,
      smt: false,
      prices: [],
      displayName: 'Intel C2Q Q8400',
    },
    {
      '@id': '/api/cpus/26',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'C2Q',
      model: 'Q9550',
      speed: 283,
      cores: 4,
      smt: false,
      prices: [],
      displayName: 'Intel C2Q Q9550',
    },
    {
      '@id': '/api/cpus/27',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/1',
        '@type': 'CpuVendor',
        name: 'Intel',
      },
      family: 'Celeron',
      model: 'G1620',
      speed: 270,
      cores: 2,
      smt: false,
      prices: [],
      displayName: 'Intel Celeron G1620',
    },
    {
      '@id': '/api/cpus/28',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/2',
        '@type': 'CpuVendor',
        name: 'AMD',
      },
      family: 'X2',
      model: '240',
      speed: 280,
      cores: 2,
      smt: false,
      prices: [],
      displayName: 'AMD X2 240',
    },
    {
      '@id': '/api/cpus/29',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/2',
        '@type': 'CpuVendor',
        name: 'AMD',
      },
      family: 'X2',
      model: '250',
      speed: 300,
      cores: 2,
      smt: false,
      prices: [],
      displayName: 'AMD X2 250',
    },
    {
      '@id': '/api/cpus/30',
      '@type': 'Cpu',
      vendor: {
        '@id': '/api/cpu_vendors/2',
        '@type': 'CpuVendor',
        name: 'AMD',
      },
      family: 'X4',
      model: 'Phenon 955',
      speed: 320,
      cores: 4,
      smt: false,
      prices: [],
      displayName: 'AMD X4 Phenon 955',
    },
  ],
  'hydra:totalItems': 30,
}
