export default {
  '@context': '/api/contexts/OperatingSystem',
  '@id': '/api/operating_systems',
  '@type': 'hydra:Collection',
  'hydra:member': [
    {
      '@id': '/api/operating_systems/1',
      '@type': 'OperatingSystem',
      id: 1,
      category: {
        '@id': '/api/operating_system_categories/1',
        '@type': 'OperatingSystemCategory',
        name: 'Windows',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: false,
      distribution: 'Windows 2008 R2',
      version: 'Enterprise (TRIAL-key)',
      popular: false,
      displayName: 'Windows 2008 R2 Enterprise (TRIAL-key)',
    },
    {
      '@id': '/api/operating_systems/2',
      '@type': 'OperatingSystem',
      id: 2,
      category: {
        '@id': '/api/operating_system_categories/1',
        '@type': 'OperatingSystemCategory',
        name: 'Windows',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: false,
      distribution: 'Windows 2008 R2',
      version: 'Standard (TRIAL-key)',
      popular: false,
      displayName: 'Windows 2008 R2 Standard (TRIAL-key)',
    },
    {
      '@id': '/api/operating_systems/3',
      '@type': 'OperatingSystem',
      id: 3,
      category: {
        '@id': '/api/operating_system_categories/1',
        '@type': 'OperatingSystemCategory',
        name: 'Windows',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: false,
      distribution: 'Windows 2012 R2',
      version: 'Datacenter (per CPU license)',
      popular: false,
      displayName: 'Windows 2012 R2 Datacenter (per CPU license)',
    },
    {
      '@id': '/api/operating_systems/4',
      '@type': 'OperatingSystem',
      id: 4,
      category: {
        '@id': '/api/operating_system_categories/1',
        '@type': 'OperatingSystemCategory',
        name: 'Windows',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: false,
      distribution: 'Windows 2012 R2',
      version: 'Datacenter (TRIAL-key)',
      popular: false,
      displayName: 'Windows 2012 R2 Datacenter (TRIAL-key)',
    },
    {
      '@id': '/api/operating_systems/5',
      '@type': 'OperatingSystem',
      id: 5,
      category: {
        '@id': '/api/operating_system_categories/1',
        '@type': 'OperatingSystemCategory',
        name: 'Windows',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: false,
      distribution: 'Windows 2012 R2',
      version: 'Standard (per CPU license)',
      popular: false,
      displayName: 'Windows 2012 R2 Standard (per CPU license)',
    },
    {
      '@id': '/api/operating_systems/6',
      '@type': 'OperatingSystem',
      id: 6,
      category: {
        '@id': '/api/operating_system_categories/1',
        '@type': 'OperatingSystemCategory',
        name: 'Windows',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: false,
      distribution: 'Windows 2012 R2',
      version: 'Standard (TRIAL-key)',
      popular: false,
      displayName: 'Windows 2012 R2 Standard (TRIAL-key)',
    },
    {
      '@id': '/api/operating_systems/7',
      '@type': 'OperatingSystem',
      id: 7,
      category: {
        '@id': '/api/operating_system_categories/1',
        '@type': 'OperatingSystemCategory',
        name: 'Windows',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: false,
      distribution: 'Windows 2016',
      version: 'Datacenter (per CPU core license)',
      popular: false,
      displayName: 'Windows 2016 Datacenter (per CPU core license)',
    },
    {
      '@id': '/api/operating_systems/8',
      '@type': 'OperatingSystem',
      id: 8,
      category: {
        '@id': '/api/operating_system_categories/1',
        '@type': 'OperatingSystemCategory',
        name: 'Windows',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: false,
      distribution: 'Windows 2016',
      version: 'Datacenter (TRIAL-key)',
      popular: false,
      displayName: 'Windows 2016 Datacenter (TRIAL-key)',
    },
    {
      '@id': '/api/operating_systems/9',
      '@type': 'OperatingSystem',
      id: 9,
      category: {
        '@id': '/api/operating_system_categories/1',
        '@type': 'OperatingSystemCategory',
        name: 'Windows',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: false,
      distribution: 'Windows 2016',
      version: 'Standard (per CPU core license)',
      popular: false,
      displayName: 'Windows 2016 Standard (per CPU core license)',
    },
    {
      '@id': '/api/operating_systems/10',
      '@type': 'OperatingSystem',
      id: 10,
      category: {
        '@id': '/api/operating_system_categories/1',
        '@type': 'OperatingSystemCategory',
        name: 'Windows',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: false,
      distribution: 'Windows 2016',
      version: 'Standard (TRIAL-key)',
      popular: false,
      displayName: 'Windows 2016 Standard (TRIAL-key)',
    },
    {
      '@id': '/api/operating_systems/11',
      '@type': 'OperatingSystem',
      id: 11,
      category: {
        '@id': '/api/operating_system_categories/1',
        '@type': 'OperatingSystemCategory',
        name: 'Windows',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: false,
      distribution: 'Windows 2019',
      version: 'Datacenter (per CPU core license)',
      popular: false,
      displayName: 'Windows 2019 Datacenter (per CPU core license)',
    },
    {
      '@id': '/api/operating_systems/12',
      '@type': 'OperatingSystem',
      id: 12,
      category: {
        '@id': '/api/operating_system_categories/1',
        '@type': 'OperatingSystemCategory',
        name: 'Windows',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: false,
      distribution: 'Windows 2019',
      version: 'Datacenter (TRIAL-key)',
      popular: false,
      displayName: 'Windows 2019 Datacenter (TRIAL-key)',
    },
    {
      '@id': '/api/operating_systems/13',
      '@type': 'OperatingSystem',
      id: 13,
      category: {
        '@id': '/api/operating_system_categories/1',
        '@type': 'OperatingSystemCategory',
        name: 'Windows',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: false,
      distribution: 'Windows 2019',
      version: 'Standard (per CPU core license)',
      popular: false,
      displayName: 'Windows 2019 Standard (per CPU core license)',
    },
    {
      '@id': '/api/operating_systems/14',
      '@type': 'OperatingSystem',
      id: 14,
      category: {
        '@id': '/api/operating_system_categories/1',
        '@type': 'OperatingSystemCategory',
        name: 'Windows',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: false,
      distribution: 'Windows 2019',
      version: 'Standard (TRIAL-key)',
      popular: false,
      displayName: 'Windows 2019 Standard (TRIAL-key)',
    },
    {
      '@id': '/api/operating_systems/15',
      '@type': 'OperatingSystem',
      id: 15,
      category: {
        '@id': '/api/operating_system_categories/2',
        '@type': 'OperatingSystemCategory',
        name: 'Unix',
      },
      softwareRaid: true,
      cPanel: true,
      directAdmin: true,
      distribution: 'CentOS',
      version: '6.x',
      popular: true,
      displayName: 'CentOS 6.x',
    },
    {
      '@id': '/api/operating_systems/16',
      '@type': 'OperatingSystem',
      id: 16,
      category: {
        '@id': '/api/operating_system_categories/2',
        '@type': 'OperatingSystemCategory',
        name: 'Unix',
      },
      softwareRaid: true,
      cPanel: true,
      directAdmin: true,
      distribution: 'CentOS',
      version: '7.x',
      popular: true,
      displayName: 'CentOS 7.x',
    },
    {
      '@id': '/api/operating_systems/17',
      '@type': 'OperatingSystem',
      id: 17,
      category: {
        '@id': '/api/operating_system_categories/2',
        '@type': 'OperatingSystemCategory',
        name: 'Unix',
      },
      softwareRaid: true,
      cPanel: true,
      directAdmin: true,
      distribution: 'CloudLinux',
      version: '',
      popular: false,
      displayName: 'CloudLinux ',
    },
    {
      '@id': '/api/operating_systems/18',
      '@type': 'OperatingSystem',
      id: 18,
      category: {
        '@id': '/api/operating_system_categories/2',
        '@type': 'OperatingSystemCategory',
        name: 'Unix',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: true,
      distribution: 'Debian',
      version: '8.x (jessie)',
      popular: true,
      displayName: 'Debian 8.x (jessie)',
    },
    {
      '@id': '/api/operating_systems/19',
      '@type': 'OperatingSystem',
      id: 19,
      category: {
        '@id': '/api/operating_system_categories/2',
        '@type': 'OperatingSystemCategory',
        name: 'Unix',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: true,
      distribution: 'Debian',
      version: '9.x (stretch)',
      popular: true,
      displayName: 'Debian 9.x (stretch)',
    },
    {
      '@id': '/api/operating_systems/20',
      '@type': 'OperatingSystem',
      id: 20,
      category: {
        '@id': '/api/operating_system_categories/2',
        '@type': 'OperatingSystemCategory',
        name: 'Unix',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: true,
      distribution: 'Debian',
      version: '10.x (buster)',
      popular: true,
      displayName: 'Debian 10.x (buster)',
    },
    {
      '@id': '/api/operating_systems/21',
      '@type': 'OperatingSystem',
      id: 21,
      category: {
        '@id': '/api/operating_system_categories/2',
        '@type': 'OperatingSystemCategory',
        name: 'Unix',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: true,
      distribution: 'FreeBSD',
      version: '11.x',
      popular: false,
      displayName: 'FreeBSD 11.x',
    },
    {
      '@id': '/api/operating_systems/22',
      '@type': 'OperatingSystem',
      id: 22,
      category: {
        '@id': '/api/operating_system_categories/2',
        '@type': 'OperatingSystemCategory',
        name: 'Unix',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: false,
      distribution: 'FreeBSD',
      version: '12.x',
      popular: false,
      displayName: 'FreeBSD 12.x',
    },
    {
      '@id': '/api/operating_systems/23',
      '@type': 'OperatingSystem',
      id: 23,
      category: {
        '@id': '/api/operating_system_categories/2',
        '@type': 'OperatingSystemCategory',
        name: 'Unix',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: true,
      distribution: 'Ubuntu',
      version: '14.04',
      popular: false,
      displayName: 'Ubuntu 14.04',
    },
    {
      '@id': '/api/operating_systems/24',
      '@type': 'OperatingSystem',
      id: 24,
      category: {
        '@id': '/api/operating_system_categories/2',
        '@type': 'OperatingSystemCategory',
        name: 'Unix',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: true,
      distribution: 'Ubuntu',
      version: '16.04',
      popular: true,
      displayName: 'Ubuntu 16.04',
    },
    {
      '@id': '/api/operating_systems/25',
      '@type': 'OperatingSystem',
      id: 25,
      category: {
        '@id': '/api/operating_system_categories/2',
        '@type': 'OperatingSystemCategory',
        name: 'Unix',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: true,
      distribution: 'Ubuntu',
      version: '18.04',
      popular: true,
      displayName: 'Ubuntu 18.04',
    },
    {
      '@id': '/api/operating_systems/26',
      '@type': 'OperatingSystem',
      id: 26,
      category: {
        '@id': '/api/operating_system_categories/3',
        '@type': 'OperatingSystemCategory',
        name: 'Virtualization',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: false,
      distribution: 'Proxmox VE',
      version: '5.x',
      popular: false,
      displayName: 'Proxmox VE 5.x',
    },
    {
      '@id': '/api/operating_systems/27',
      '@type': 'OperatingSystem',
      id: 27,
      category: {
        '@id': '/api/operating_system_categories/3',
        '@type': 'OperatingSystemCategory',
        name: 'Virtualization',
      },
      softwareRaid: false,
      cPanel: false,
      directAdmin: false,
      distribution: 'VMWare ESXi',
      version: '5.5',
      popular: false,
      displayName: 'VMWare ESXi 5.5',
    },
    {
      '@id': '/api/operating_systems/28',
      '@type': 'OperatingSystem',
      id: 28,
      category: {
        '@id': '/api/operating_system_categories/3',
        '@type': 'OperatingSystemCategory',
        name: 'Virtualization',
      },
      softwareRaid: false,
      cPanel: false,
      directAdmin: false,
      distribution: 'VMWare ESXi',
      version: '6.0',
      popular: false,
      displayName: 'VMWare ESXi 6.0',
    },
    {
      '@id': '/api/operating_systems/29',
      '@type': 'OperatingSystem',
      id: 29,
      category: {
        '@id': '/api/operating_system_categories/3',
        '@type': 'OperatingSystemCategory',
        name: 'Virtualization',
      },
      softwareRaid: false,
      cPanel: false,
      directAdmin: false,
      distribution: 'VMWare ESXi',
      version: '6.5',
      popular: true,
      displayName: 'VMWare ESXi 6.5',
    },
    {
      '@id': '/api/operating_systems/30',
      '@type': 'OperatingSystem',
      id: 30,
      category: {
        '@id': '/api/operating_system_categories/3',
        '@type': 'OperatingSystemCategory',
        name: 'Virtualization',
      },
      softwareRaid: false,
      cPanel: false,
      directAdmin: false,
      distribution: 'VMWare ESXi',
      version: '6.7',
      popular: true,
      displayName: 'VMWare ESXi 6.7',
    },
    {
      '@id': '/api/operating_systems/31',
      '@type': 'OperatingSystem',
      id: 31,
      category: {
        '@id': '/api/operating_system_categories/3',
        '@type': 'OperatingSystemCategory',
        name: 'Virtualization',
      },
      softwareRaid: true,
      cPanel: false,
      directAdmin: false,
      distribution: 'XenServer',
      version: '7.5',
      popular: false,
      displayName: 'XenServer 7.5',
    },
  ],
  'hydra:totalItems': 31,
}
