export default {
  '@context': '/api/contexts/Price',
  '@id': '/api/prices',
  '@type': 'hydra:Collection',
  'hydra:member': [
    {
      '@id': '/api/prices/1',
      '@type': 'Price',
      id: 1,
      location: '/api/locations/1',
      amount: 25000,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/2',
      '@type': 'Price',
      id: 2,
      location: '/api/locations/1',
      amount: 42500,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/3',
      '@type': 'Price',
      id: 3,
      location: '/api/locations/1',
      amount: 60000,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/4',
      '@type': 'Price',
      id: 4,
      location: '/api/locations/1',
      amount: 77500,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/5',
      '@type': 'Price',
      id: 5,
      location: '/api/locations/1',
      amount: 89900,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/6',
      '@type': 'Price',
      id: 6,
      location: '/api/locations/1',
      amount: 4000,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/7',
      '@type': 'Price',
      id: 7,
      location: '/api/locations/2',
      amount: 4400,
      currency: {
        currencyIsoCode: 'USD',
        symbol: '$',
      },
    },
    {
      '@id': '/api/prices/8',
      '@type': 'Price',
      id: 8,
      location: '/api/locations/1',
      amount: 5000,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/9',
      '@type': 'Price',
      id: 9,
      location: '/api/locations/2',
      amount: 5500,
      currency: {
        currencyIsoCode: 'USD',
        symbol: '$',
      },
    },
    {
      '@id': '/api/prices/10',
      '@type': 'Price',
      id: 10,
      location: '/api/locations/1',
      amount: 500,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/11',
      '@type': 'Price',
      id: 11,
      location: '/api/locations/1',
      amount: 4000,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/12',
      '@type': 'Price',
      id: 12,
      location: '/api/locations/1',
      amount: 100,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/13',
      '@type': 'Price',
      id: 13,
      location: '/api/locations/1',
      amount: 100,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/14',
      '@type': 'Price',
      id: 14,
      location: '/api/locations/2',
      amount: 125,
      currency: {
        currencyIsoCode: 'USD',
        symbol: '$',
      },
    },
    {
      '@id': '/api/prices/15',
      '@type': 'Price',
      id: 15,
      location: '/api/locations/1',
      amount: 2500,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/16',
      '@type': 'Price',
      id: 16,
      location: '/api/locations/2',
      amount: 3000,
      currency: {
        currencyIsoCode: 'USD',
        symbol: '$',
      },
    },
    {
      '@id': '/api/prices/17',
      '@type': 'Price',
      id: 17,
      location: '/api/locations/1',
      amount: 100,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/18',
      '@type': 'Price',
      id: 18,
      location: '/api/locations/2',
      amount: 110,
      currency: {
        currencyIsoCode: 'USD',
        symbol: '$',
      },
    },
    {
      '@id': '/api/prices/19',
      '@type': 'Price',
      id: 19,
      location: '/api/locations/1',
      amount: 850,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/20',
      '@type': 'Price',
      id: 20,
      location: '/api/locations/2',
      amount: 935,
      currency: {
        currencyIsoCode: 'USD',
        symbol: '$',
      },
    },
    {
      '@id': '/api/prices/21',
      '@type': 'Price',
      id: 21,
      location: '/api/locations/1',
      amount: 200,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/22',
      '@type': 'Price',
      id: 22,
      location: '/api/locations/2',
      amount: 400,
      currency: {
        currencyIsoCode: 'USD',
        symbol: '$',
      },
    },
    {
      '@id': '/api/prices/23',
      '@type': 'Price',
      id: 23,
      location: '/api/locations/1',
      amount: 5500,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/24',
      '@type': 'Price',
      id: 24,
      location: '/api/locations/1',
      amount: 12500,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/25',
      '@type': 'Price',
      id: 25,
      location: '/api/locations/1',
      amount: 50000,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/26',
      '@type': 'Price',
      id: 26,
      location: '/api/locations/1',
      amount: 99900,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/27',
      '@type': 'Price',
      id: 27,
      location: '/api/locations/1',
      amount: 250000,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/28',
      '@type': 'Price',
      id: 28,
      location: '/api/locations/1',
      amount: 500000,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/29',
      '@type': 'Price',
      id: 29,
      location: '/api/locations/1',
      amount: 9900,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/30',
      '@type': 'Price',
      id: 30,
      location: '/api/locations/1',
      amount: 32400,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/31',
      '@type': 'Price',
      id: 31,
      location: '/api/locations/1',
      amount: 99900,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/32',
      '@type': 'Price',
      id: 32,
      location: '/api/locations/1',
      amount: 199800,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/33',
      '@type': 'Price',
      id: 33,
      location: '/api/locations/1',
      amount: 449900,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/34',
      '@type': 'Price',
      id: 34,
      location: '/api/locations/1',
      amount: 899900,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/35',
      '@type': 'Price',
      id: 35,
      location: '/api/locations/1',
      amount: 1000,
      currency: {
        currencyIsoCode: 'EUR',
        symbol: '€',
      },
    },
    {
      '@id': '/api/prices/36',
      '@type': 'Price',
      id: 36,
      location: '/api/locations/2',
      amount: 5000,
      currency: {
        currencyIsoCode: 'USD',
        symbol: '$',
      },
    },
  ],
  'hydra:totalItems': 36,
}
