export default {
  '@context': '/api/contexts/StorageDrive',
  '@id': '/api/storage_drives',
  '@type': 'hydra:Collection',
  'hydra:member': [
    {
      '@id': '/api/storage_drives/1',
      '@type': 'StorageDrive',
      type: 'hdd',
      name: '500GB HDD SATA III 7200rpm',
      gbAmount: 500,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/2',
      '@type': 'StorageDrive',
      type: 'hdd',
      name: '1TB HDD SATA III 7200rpm',
      gbAmount: 1000,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/3',
      '@type': 'StorageDrive',
      type: 'hdd',
      name: '2TB HDD SATA III 7200rpm',
      gbAmount: 2000,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/4',
      '@type': 'StorageDrive',
      type: 'hdd',
      name: '4TB HDD SATA III 7200rpm',
      gbAmount: 4000,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/5',
      '@type': 'StorageDrive',
      type: 'hdd',
      name: '6TB HDD SATA III 7200rpm',
      gbAmount: 6000,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/6',
      '@type': 'StorageDrive',
      type: 'hdd',
      name: '8TB HDD SATA III 7200rpm',
      gbAmount: 8000,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/7',
      '@type': 'StorageDrive',
      type: 'hdd',
      name: '10TB HDD SATA III 7200rpm',
      gbAmount: 10000,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/8',
      '@type': 'StorageDrive',
      type: 'hdd',
      name: '12TB HDD SATA III 7200rpm',
      gbAmount: 12000,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/9',
      '@type': 'StorageDrive',
      type: 'hdd',
      name: '14TB HDD SATA III 7200rpm',
      gbAmount: 14000,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/10',
      '@type': 'StorageDrive',
      type: 'ssd',
      name: '120GB SSD',
      gbAmount: 120,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/11',
      '@type': 'StorageDrive',
      type: 'ssd',
      name: '240GB Intel Enterprise SSD',
      gbAmount: 240,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/12',
      '@type': 'StorageDrive',
      type: 'ssd',
      name: '250GB SSD',
      gbAmount: 250,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/13',
      '@type': 'StorageDrive',
      type: 'ssd',
      name: '480GB Intel Enterprise SSD',
      gbAmount: 480,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/14',
      '@type': 'StorageDrive',
      type: 'ssd',
      name: '500GB SSD',
      gbAmount: 500,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/15',
      '@type': 'StorageDrive',
      type: 'ssd',
      name: '960GB Intel Enterprise SSD',
      gbAmount: 960,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/16',
      '@type': 'StorageDrive',
      type: 'ssd',
      name: '1TB SSD',
      gbAmount: 1000,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/17',
      '@type': 'StorageDrive',
      type: 'ssd',
      name: '1.92TB Intel Enterprise SSD',
      gbAmount: 1920,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/18',
      '@type': 'StorageDrive',
      type: 'ssd',
      name: '2TB SSD',
      gbAmount: 2000,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/19',
      '@type': 'StorageDrive',
      type: 'ssd',
      name: '3.84TB Intel Enterprise SSD',
      gbAmount: 3840,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/20',
      '@type': 'StorageDrive',
      type: 'ssd',
      name: '4TB SSD',
      gbAmount: 4000,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/21',
      '@type': 'StorageDrive',
      type: 'pcie-ssd',
      name: '250GB PCI-E SSD',
      gbAmount: 250,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/22',
      '@type': 'StorageDrive',
      type: 'pcie-ssd',
      name: '512GB PCI-E SSD',
      gbAmount: 512,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/23',
      '@type': 'StorageDrive',
      type: 'pcie-ssd',
      name: '1TB PCI-E SSD',
      gbAmount: 1000,
      prices: [],
      volumeDiscounts: [],
    },
    {
      '@id': '/api/storage_drives/24',
      '@type': 'StorageDrive',
      type: 'pcie-ssd',
      name: '2TB PCI-E SSD',
      gbAmount: 2000,
      prices: [],
      volumeDiscounts: [],
    },
  ],
  'hydra:totalItems': 24,
}
