export default {
  '@context': '/api/contexts/Uplink',
  '@id': '/api/uplinks',
  '@type': 'hydra:Collection',
  'hydra:member': [
    {
      '@id': '/api/uplinks/1',
      '@type': 'Uplink',
      speed: 1000,
      guaranteedSpeed: 1000,
      unmetered: true,
      platinum: false,
      prices: [],
      displayName: '1Gbit/s (1Gbit/s, Unmetered)',
    },
    {
      '@id': '/api/uplinks/2',
      '@type': 'Uplink',
      speed: 10000,
      guaranteedSpeed: 2000,
      unmetered: true,
      platinum: false,
      prices: [
        {
          '@id': '/api/prices/24',
          '@type': 'Price',
          location: '/api/locations/1',
          amount: 12500,
        },
      ],
      displayName: '10Gbit/s (2Gbit/s, Unmetered)',
    },
    {
      '@id': '/api/uplinks/3',
      '@type': 'Uplink',
      speed: 10000,
      guaranteedSpeed: 5000,
      unmetered: true,
      platinum: false,
      prices: [
        {
          '@id': '/api/prices/25',
          '@type': 'Price',
          location: '/api/locations/1',
          amount: 50000,
        },
      ],
      displayName: '10Gbit/s (5Gbit/s, Unmetered)',
    },
    {
      '@id': '/api/uplinks/4',
      '@type': 'Uplink',
      speed: 10000,
      guaranteedSpeed: 10000,
      unmetered: true,
      platinum: false,
      prices: [
        {
          '@id': '/api/prices/26',
          '@type': 'Price',
          location: '/api/locations/1',
          amount: 99900,
        },
      ],
      displayName: '10Gbit/s (10Gbit/s, Unmetered)',
    },
    {
      '@id': '/api/uplinks/5',
      '@type': 'Uplink',
      speed: 40000,
      guaranteedSpeed: 20000,
      unmetered: true,
      platinum: false,
      prices: [
        {
          '@id': '/api/prices/27',
          '@type': 'Price',
          location: '/api/locations/1',
          amount: 250000,
        },
      ],
      displayName: '40Gbit/s (20Gbit/s, Unmetered)',
    },
    {
      '@id': '/api/uplinks/6',
      '@type': 'Uplink',
      speed: 40000,
      guaranteedSpeed: 40000,
      unmetered: true,
      platinum: false,
      prices: [
        {
          '@id': '/api/prices/28',
          '@type': 'Price',
          location: '/api/locations/1',
          amount: 500000,
        },
      ],
      displayName: '40Gbit/s (40Gbit/s, Unmetered)',
    },
    {
      '@id': '/api/uplinks/7',
      '@type': 'Uplink',
      speed: 1000,
      guaranteedSpeed: 1000,
      unmetered: true,
      platinum: true,
      prices: [
        {
          '@id': '/api/prices/29',
          '@type': 'Price',
          location: '/api/locations/1',
          amount: 9900,
        },
      ],
      displayName: '1Gbit/s (1Gbit/s, Unmetered, Platinum)',
    },
    {
      '@id': '/api/uplinks/8',
      '@type': 'Uplink',
      speed: 10000,
      guaranteedSpeed: 2000,
      unmetered: true,
      platinum: true,
      prices: [
        {
          '@id': '/api/prices/30',
          '@type': 'Price',
          location: '/api/locations/1',
          amount: 32400,
        },
      ],
      displayName: '10Gbit/s (2Gbit/s, Unmetered, Platinum)',
    },
    {
      '@id': '/api/uplinks/9',
      '@type': 'Uplink',
      speed: 10000,
      guaranteedSpeed: 5000,
      unmetered: true,
      platinum: true,
      prices: [
        {
          '@id': '/api/prices/31',
          '@type': 'Price',
          location: '/api/locations/1',
          amount: 99900,
        },
      ],
      displayName: '10Gbit/s (5Gbit/s, Unmetered, Platinum)',
    },
    {
      '@id': '/api/uplinks/10',
      '@type': 'Uplink',
      speed: 10000,
      guaranteedSpeed: 10000,
      unmetered: true,
      platinum: true,
      prices: [
        {
          '@id': '/api/prices/32',
          '@type': 'Price',
          location: '/api/locations/1',
          amount: 199800,
        },
      ],
      displayName: '10Gbit/s (10Gbit/s, Unmetered, Platinum)',
    },
    {
      '@id': '/api/uplinks/11',
      '@type': 'Uplink',
      speed: 40000,
      guaranteedSpeed: 20000,
      unmetered: true,
      platinum: true,
      prices: [
        {
          '@id': '/api/prices/33',
          '@type': 'Price',
          location: '/api/locations/1',
          amount: 449900,
        },
      ],
      displayName: '40Gbit/s (20Gbit/s, Unmetered, Platinum)',
    },
    {
      '@id': '/api/uplinks/12',
      '@type': 'Uplink',
      speed: 40000,
      guaranteedSpeed: 40000,
      unmetered: true,
      platinum: true,
      prices: [
        {
          '@id': '/api/prices/34',
          '@type': 'Price',
          location: '/api/locations/1',
          amount: 899900,
        },
      ],
      displayName: '40Gbit/s (40Gbit/s, Unmetered, Platinum)',
    },
    {
      '@id': '/api/uplinks/13',
      '@type': 'Uplink',
      speed: 100,
      guaranteedSpeed: 100,
      unmetered: false,
      platinum: false,
      prices: [],
      displayName: '100Mbit/s (100Mbit/s)',
    },
    {
      '@id': '/api/uplinks/14',
      '@type': 'Uplink',
      speed: 1000,
      guaranteedSpeed: 1000,
      unmetered: false,
      platinum: false,
      prices: [
        {
          '@id': '/api/prices/35',
          '@type': 'Price',
          location: '/api/locations/1',
          amount: 1000,
        },
        {
          '@id': '/api/prices/36',
          '@type': 'Price',
          location: '/api/locations/2',
          amount: 5000,
        },
      ],
      displayName: '1Gbit/s (1Gbit/s)',
    },
  ],
  'hydra:totalItems': 14,
}
